### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by Anniepoo** [larsyencken/marelle#18]
slight issue with installation instructions - if you copy/paste step 3 into terminal, it swallows the $@

exec swipl -q -t main -s ~/.local/marelle/marelle.pl "$@"

becomes 

exec swipl -q -t main -s ~/.local/marelle/marelle.pl ""

Since I assume it's working for you, need something more complex than escaping the $.  So not sure
how to proceed, hence issue rather than pr.

8cD

**Comment by larsyencken** [comment]
Well picked up! It turns out this was escaped properly in the bootstrap scripts, but not in the README: https://github.com/larsyencken/marelle/blob/master/bootstrap_dev.sh#L118
