### ISSUE TITLE
modules

### ISSUE THREAD

**Issue by Anniepoo** [larsyencken/marelle#20]
Best practice for modern Prolog code is to put everything in a module.

It's a major change, but I'd like to send a PR that puts everything in a module, and pulls the numbers from the names of the .pl files in core.

**Comment by Anniepoo** [comment]
I did pull the numbers. After converting to modules, I convinced myself that's not such a good idea.

**Comment by larsyencken** [comment]
I think it's hard to to separation of concerns in the one big module, it feels easier to make sense of it in smaller pieces. I'm guessing you came to the same conclusion :)

**Comment by Anniepoo** [comment]
Paulo Moura suggested the solution of doing term_expansion just in files coming from paths with marelle-deps in them.
Re modules - I meant 'the code is currently not in modules. I intend to put them in different modules for separation of concerns'
